### PR TITLE
Refactor to using TypeScript

### PR DESCRIPTION
**Pull request by mtraynham**
This moves the entire project over to using TypeScript exclusively.  Git will currently ignore any JavaScript files.  On `npm run build`, all TypeScript files will be converted into JavaScript and can be deployed to NPM.

I've also added the `package-lock.json` file to the source repo.

The only other real difference here, this has Peer Dependencies on Tslint 5+ & and Webpack 2+, it does not support Tslint 4.X and Webpack 1.X.  They're deprecated versions and this is probably a big enough change to cut them off.

Pending any comments, I'll gladly make the changes to the README if suggested.

### CODE REVIEW

**Comment by blacksonic** [comment]
Is it possible to separate it to separate PRs?
It introduces several big changes, dependencies, the plugin and typescript conversion.
Webpack 1 is still supported, why should we cut it off?

**Comment by mtraynham** [comment]
I can add back Webpack 1.  How would you prefer I split out the PRs?  The two commits are there, one is for the TypeScript migration and second is for the Plugin.  I can make those separate?

**Comment by mtraynham** [comment]
So I updated #78 to fix the `typeCheck` issue.  

As I'm hoping that one does get accepted, and this is more of a refactor, I've rebased this PR on top of that branch so I don't have to redo that migration.  If you do end up accepting that one, the first commit of this would essentially be master and would go away.  We can further discuss breaking down this PR as you see fit.

I've also added back Webpack 1.X to peer deps.

**Comment by blacksonic** [comment]
I would submit the typecheck fix in a separate pull request, not join it typescript refactor and adding Webpack 1 peerdeps, which is now a deprecated version

**Pull request closed without merging**
