### PR TITLE
TSlint v5 compatibility

### LINKED ISSUE #67: Tslint should be of version 4+
I tried to update tslint to version 5.0.0, but I got an error on build

ERROR in ./src/polyfills.browser.ts
Module build failed: Error: Tslint should be of version 4+
    at Object.module.exports (\node_modules\tslint-loader\index.js:121:11)
 @ multi (webpack)-dev-server/client?./src/polyfills.browser.ts

version of tslint-loader: 3.4.3

### PR DESCRIPTION
**Pull request by bastienmoulia**
Replace tslint dependencies `^4.0.0` by `>=4.0.0`.

close #67

### CODE REVIEW

**Comment by blacksonic** [comment]
@bastienmoulia Can you fix the test failures?

**Comment by bastienmoulia** [comment]
@blacksonic I don't know if it is better to change the expected value or to change the config and the test.

**Comment by blacksonic** [comment]
There is something wrong with the code, it had a stack trace with the error.

**Comment by blacksonic** [comment]
```
./test/app/engine.ts\n(Emitted value instead of an instance of Error) [8, 1]: Calls to 'console.log' are not allowed.\n\nNonErrorEmittedError: (Emitted value instead of an instance of Error) [8, 1]: Calls to 'console.log' are not allowed.\n\n    at emitError (/home/travis/build/wbuchwalter/tslint-loader/node_modules/webpack/lib/NormalModule.js:119:14)\n    at report (/home/travis/build/wbuchwalter/tslint-loader/index.js:67:3)\n    at lint (/home/travis/build/wbuchwalter/tslint-loader/index.js:62:3)\n    at Object.module.exports (/home/travis/build/wbuchwalter/tslint-loader/index.js:125:3)
```

**Comment by jskrzypek** [comment]
This is failing because webpack is expecting an `Error` instance to be passed to `emitError()`/ `emitWarning()`: see https://github.com/webpack/webpack/blob/master/lib/NormalModule.js#L112-L121
I think the correct solution may be to actually to patch the loader's code itself and just create a new error from the `result.output` in `report()`.

**Comment by jskrzypek** [comment]
I made a PR (#70) that provides a properly formatted error instance to emitError & emitWarning as well as upgrading the semver for tslint

**Pull request closed without merging**
