### PR TITLE
use `tslintConfig.findConfiguration` to retrieve local config

### LINKED ISSUE #29: the "extend" part of the "tslint.json" is ignored/must be resolved
when looking at what is passed to the `Linter` in the loader, it looks as if the `extend` part of the `tslint.json` is ignored.

### PR DESCRIPTION
**Pull request by timse**
this should fix #29 and #23

### CODE REVIEW

**Comment by wbuchwalter** [comment]
Thanks!

**Comment by wbuchwalter** [comment]
Released under `2.1.5`

**Comment by timse** [comment]
👍  thanks for merging so quickly :)!

**Comment by MrHayato** [comment]
This is a breaking change. My tslint.json no longer can be specified as an option, and tslint's `findConfiguration` can't find my configuration because it's not in an ancestor folder. We need the ability to specify where the tslint.json file location is.

**Comment by piq9117** [comment]
same problem with @MrHayato

**Pull request merged**
